Update Dockerfile

diff --git a/webapps/etherpad/v1.7/Dockerfile b/webapps/etherpad/v1.7/Dockerfile
--- a/webapps/etherpad/v1.7/Dockerfile
+++ b/webapps/etherpad/v1.7/Dockerfile
@@ -17,14 +17,33 @@ RUN echo -e "\n[i] Install build packages \n" \
         python \
         libressl \
         zlib \
-        libuv
-
-ADD scripts/s6-overlay.sh /tmp/s6-overlay.sh
-RUN chmod +x /tmp/s6-overlay.sh && \
-    /tmp/s6-overlay.sh
-
-WORKDIR /opt
-RUN curl -L https://github.com/ether/etherpad-lite/archive/${ETHERPAD_VERSION}.tar.gz -o etherpad.tar.gz && \
+        libuv && \
+    \
+    # s6-overlay \
+    echo -e "\n[i] Install s6-overlay\n" && \
+    GPG="DB30 1BA3 F6F8 07E0 D0E6  CCB8 6101 B278 3B2F D161" && \
+    S6OVERLAY=$(curl -s https://api.github.com/repos/just-containers/s6-overlay/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")') && \
+    if [ $(uname -m) == "armv6l" ] || [ $(uname -m) == "armv7l" ]; then ARCHTAG=armhf ; elif [ $(uname -m) == "aarch64" ]; then ARCHTAG=aarch64 ; elif [ $(uname -m) == "x86_64" ]; then ARCHTAG=amd64 ; fi && \
+    curl -o /tmp/s6-overlay.tar.gz -L https://github.com/just-containers/s6-overlay/releases/download/${S6OVERLAY}/s6-overlay-${ARCHTAG}.tar.gz && \
+    curl -o /tmp/s6-overlay.tar.gz.sig -L https://github.com/just-containers/s6-overlay/releases/download/${S6OVERLAY}/s6-overlay-${ARCHTAG}.tar.gz.sig && \
+    curl https://keybase.io/justcontainers/key.asc | gpg --import && \
+    FINGERPRINT="$(LANG=C gpg --verify /tmp/s6-overlay.tar.gz.sig /tmp/s6-overlay.tar.gz 2>&1 | sed -n "s#Primary key fingerprint: \(.*\)#\1#p")" && \
+    gpg --verify /tmp/s6-overlay.tar.gz.sig /tmp/s6-overlay.tar.gz && \
+    if [ -z "${FINGERPRINT}" ]; then echo "[!!] Invalid GPG signature!" && exit 1; fi && \
+    if [ "${FINGERPRINT}" != "${GPG}" ]; then echo "[!!] Wrong GPG fingerprint!" && exit 1; fi && \
+    echo "[i] All seems good, now unpacking s6-overlay.tar.gz" && \
+    tar xzf /tmp/s6-overlay.tar.gz -C / && \
+    \
+    # socklog-overlay \
+    echo -e "\n[i] Install socklog-overlay\n" && \
+    SOCKLOG=$(curl -s https://api.github.com/repos/just-containers/socklog-overlay/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")') && \
+    if [ $(uname -m) == "armv6l" ] || [ $(uname -m) == "armv7l" ]; then ARCHTAG=armhf ; elif [ $(uname -m) == "aarch64" ]; then ARCHTAG=aarch64 ; elif [ $(uname -m) == "x86_64" ]; then ARCHTAG=amd64 ; fi && \
+    curl -o /tmp/socklog-overlay-${ARCHTAG}.tar.gz -L https://github.com/just-containers/socklog-overlay/releases/download/${SOCKLOG}/socklog-overlay-${ARCHTAG}.tar.gz && \
+    tar xzf /tmp/socklog-overlay-${ARCHTAG}.tar.gz -C / && \
+    \
+    # Etherpad \
+    cd /opt && \
+    curl -L https://github.com/ether/etherpad-lite/archive/${ETHERPAD_VERSION}.tar.gz -o etherpad.tar.gz && \
     tar -xvzf etherpad.tar.gz && \
     cd etherpad-lite-${ETHERPAD_VERSION} && \
     rsync \
@@ -44,25 +63,32 @@ RUN curl -L https://github.com/ether/etherpad-lite/archive/${ETHERPAD_VERSION}.t
 	--exclude 'start.bat'\
 	--exclude 'tests/'\
 	-a . /opt/etherpad && \
-    rm -rf etherpad-lite-${ETHERPAD_VERSION} etherpad.tar.gz
-
-WORKDIR /opt/etherpad
-ADD scripts/ep_modules.sh /tmp/ep_modules.sh
-RUN chmod +x /tmp/ep_modules.sh && \
-    /tmp/ep_modules.sh && \
-    rm /tmp/ep_modules.sh && \
+    rm -rf etherpad-lite-${ETHERPAD_VERSION} etherpad.tar.gz && \
+    cd /opt/etherpad && \
+    echo -e "\n\n[i] Install awesome plugins \n" && \
+    npm install \
+	ep_adminpads \
+	ep_font_color \
+        ep_headings2 \
+	ep_historicalsearch \
+	ep_horizontal_line \
+        ep_markdown \
+	ep_markdownify \
+	ep_offline_edit \
+	ep_page_view \
+	ep_spellcheck \
+	ep_timesliderdiff && \
     bin/installDeps.sh && \
     cd src && \
     npm i --package-lock-only && \
-    npm audit fix --force
-
-# Cleanup and security fixes
-RUN curl -o /tmp/cleanup.sh -L https://gist.githubusercontent.com/christiansteier/dd8c5544c69504d29bd938726691255b/raw/5317638ec64c0e8c3d22cd9965237a452bf82895/docker-alpine-cleanup.sh && \
-    chmod +x /tmp/cleanup.sh && \
+    npm audit fix --force && \
+    \
+    # Cleanup \
     apk del --purge build-dependencies && \
-    /tmp/cleanup.sh && \
-    rm -rf /tmp/*
+    rm -rf /var/cache/apk/* /usr/share/doc /usr/share/man/ /usr/share/info/* /var/cache/man/* /tmp/* /etc/fstab
 
 # copy local files
 COPY root/ /
+
+WORKDIR /opt/etherpad
 ENTRYPOINT ["/init"]
